### ISSUE TITLE
Tweak theme for long tables

### ISSUE THREAD

**Issue by bric3** [bric3/bric3.github.io#10]
This is particularly useful for mobiles to nudge about the fact that table can be horizontally scrolled.

On [foojay.io](https://foojay.io/command-line-arguments/openjdk-11/?tab=alloptions), tables have ability, there is this pseudo element :

```css
.table-box::after {
    content: '';
    background: linear-gradient(270deg, #FFFFFF 49.95%, rgba(255, 255, 255, 0.5) 100%);
    width: 54px;
    position: absolute;
    top: 0;
    bottom: 0;
    right: 0;
}
```

I found this questions : 
* https://stackoverflow.com/questions/38542163/pure-css-scroll-shadows
* https://stackoverflow.com/questions/5115427/how-can-i-add-a-box-shadow-on-one-side-of-an-element

Other example on [https://viqueen.org](https://viqueen.org/articles/Will-it-run--...-But-Should-it-even-compile-/)

<img width="997" alt="image" src="https://user-images.githubusercontent.com/803621/188471850-7a84c8e5-da73-473a-bdba-90813bcbbae4.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/803621/188471900-1d528823-cc05-4e79-9de4-fb02eed2ebe1.png">

```html
<div class="code-block  css-iwznuw">
<span data-code-lang="java" data-ds--code--code-block="" class="prismjs css-1g7m763">
<code class="language-java" style="white-space: pre;">
   actual code highlight (spans)
</code>
</span>
</div>
```

This CSS rule adds the shadow on the left and right it seems, note the values are split on several line for more legibility, also some rules have been skipped, so check back with source if some rules are missing.

```css
.css-iwznuw [data-ds--code--code-block] {
    background-image:
        linear-gradient(to left, rgb(244, 245, 247) 8px, transparent 8px),
        linear-gradient(to left, rgba(9, 30, 66, 0.13) 0px, rgba(99, 114, 130, 0) 8px),
        linear-gradient(to right, rgba(9, 30, 66, 0.13) 0px, rgba(99, 114, 130, 0) 8px);
    background-attachment:
        local,
        scroll,
        scroll;
    background-position:
        100% 0px,
        100% 0px,
        0px 0px
}

.css-1g7m763 code:first-of-type {
    background-image:
        linear-gradient(to right,var(--ds--code--line-number-bg-color,var(--ds-background-neutral,#EBECF0)),var(--ds--code--line-number-bg-color,var(--ds-background-neutral,#EBECF0)) calc(2ch + 16px),transparent calc(2ch + 16px),transparent);
    padding-right: 0px !important;
}
```

* The first background seems to be used as "an overlay" over the shadow background when the span has been scrolled to the max right. It has the same color as the actual background of the code block.
* The second background seems to be the shadow effect on the right border when scrolling. It start to appear after when scrolling to left after the first background.
    <img width="40" alt="image" src="https://user-images.githubusercontent.com/803621/188476391-d392c156-08fe-4671-abd7-8036e8d61c6e.png">
* The third background seems to be the shadow effect on the left border when scrolling. It appears after the line number gutter
    <img width="120" alt="image" src="https://user-images.githubusercontent.com/803621/188475877-1d1b97e9-7293-4429-ba62-04fde90dd99a.png">

* The background on the `code:first-of-type` sets a background on the line number gutter, of the width of 2 char, it hides the background on the left.
