### ISSUE TITLE
coffee mug

### ISSUE THREAD

**Issue by bric3** [bric3/bric3.github.io#14]
Ideas : 

* [Coffee Steam](https://codepen.io/alxmrtnz/pen/jWZbey) pure css
* ![Coffee Steam GIF by SorenWorks](https://user-images.githubusercontent.com/803621/100124027-6c6efc00-2e7b-11eb-9ac1-52bcf152afbd.gif) <- target
* [https://codepen.io/knard/pen/Cyrwv](https://codepen.io/knard/pen/Cyrwv) pure css, nice
* [Coffee Cup Steam](https://codepen.io/zherring/pen/GmYzxM) pure CSS ++
* [coffee loader](https://codepen.io/BJack/pen/lpaBC)
* [Sine wave SVG line animation with cubic bézier](https://codepen.io/hey-nick/pen/KVWvJv) JS mostly ++
* [Sine Wave Experiment](https://codepen.io/pdx4d/pen/YVMKaM) HTML5 canvas / JS ++ (lib )
* [CSS Sine Waves](https://codepen.io/diessica/pen/keLBq) pure css sine wave
* [Animated canvas (sine + planes)](https://codepen.io/fuggfuggfugg/pen/GIpmq) canvas + JS ++ ([how](https://www.reddit.com/r/web_design/comments/2axfy4/inspired_by_a_wallpaper_this_is_my_first_shot/cizxbf7/?utm_source=reddit&utm_medium=web2x&context=3))
* [CSS & SVG Waves Animation](https://codepen.io/tedmcdo/pen/PqxKXg) SVG + pure css +++ 
* [Scroll wave](https://codepen.io/James0r/pen/earmgP) inline svg

**Comment by bric3** [comment]
I'd like to avoid using 3rd party libe, like three.js, even if the render is reaaly nice
* [Tutorial for animation with sine waves | three.js](https://codepen.io/pshkvsky/pen/ojxGBL)

**Comment by bric3** [comment]
Bootstraping solution : https://jsfiddle.net/9sbyajof/2/

```html
<head>
<meta charset="UTF-8">
	<title>wavy</title>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
</head>
<body>
	<div class='box'>
	  <div class='wave -one'></div>
	  <div class='wave -two'></div>
	  <div class='wave -three'></div>
	</div>
</body>
```

```css
body{
	margin: 0;
	padding: 0;
	background-color: #0e6cc4;
	overflow-x: hidden;
	overflow-y: hidden;
}


/* waves */

.box {
	position: fixed;
	top: 0;
	transform: rotate(90deg);
	left: 0;
}

.wave {
	/* top: 0; */
	/* left: 0; */
  opacity: 0.4;
  position: absolute;
  top: 3%;
  left: 10%;
  background: #0af;
  width: 1500px;
  height: 1300px;
  margin-left: -150px;
  margin-top: -250px;
  transform-origin: 50% 48%;
  border-radius: 43%;
  animation: drift 7000ms infinite linear;
}

.wave.-three {
  animation: drift 7500ms infinite linear;
	position: fixed;
	background-color: #77daff;
}

.wave.-two {
  animation: drift 3000ms infinite linear;
  opacity: 0.1;
  background: black;
	position: fixed;
}

.box::after {
  content: '';
  display: block;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: 11;
  transform: translate3d(0, 0, 0);
}

@keyframes drift {
  from { transform: rotate(0deg); }
  from { transform: rotate(360deg); }
}
```

**Comment by bric3** [comment]
Based on https://codepen.io/tedmcdo/pen/PqxKXg

```html
<div class="ocean">
  <div class="wave"></div>
  <div class="wave"></div>
</div>
```

```scss
// best seen at 1500px or less

html, body { height: 100%; }
body {
  background:radial-gradient(ellipse at center, rgba(255,254,234,1) 0%, rgba(255,254,234,1) 35%, #B7E8EB 100%);
  overflow: hidden;
}

.ocean { 
  height: 5%;
  width:100%;
  position:absolute;
  bottom:0;
  left:0;
  background: #015871;
}

.wave {
  background: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/85486/wave.svg) repeat-x; 
  position: absolute;
  top: -198px;
  width: 6400px;
  height: 198px;
  animation: wave 7s cubic-bezier( 0.36, 0.45, 0.63, 0.53) infinite;
  transform: translate3d(0, 0, 0);
}

.wave:nth-of-type(2) {
  top: -175px;
  animation: wave 7s cubic-bezier( 0.36, 0.45, 0.63, 0.53) -.125s infinite, swell 7s ease -1.25s infinite;
  opacity: 1;
}

@keyframes wave {
  0% {
    margin-left: 0;
  }
  100% {
    margin-left: -1600px;
  }
}

@keyframes swell {
  0%, 100% {
    transform: translate3d(0,-25px,0);
  }
  50% {
    transform: translate3d(0,5px,0);
  }
}
```

**Comment by bric3** [comment]
From https://www.danielefavi.com/blog/css-wave-generator/ dots

```html
<div id="wave-container" class="wave-container">
    <div class="dot" id="d1"></div>
    <div class="dot" id="d2"></div>
    <div class="dot" id="d3"></div>
    <div class="dot" id="d4"></div>
    <div class="dot" id="d5"></div>
    <div class="dot" id="d6"></div>
    <div class="dot" id="d7"></div>
    <div class="dot" id="d8"></div>
    <div class="dot" id="d9"></div>
    <div class="dot" id="d10"></div>
</div>
```

```css
#wave-container { position: relative; height: 36px; width: 132px; }

.dot {
    transform-origin: 50% 50%;
    height: 6px; width: 6px;
    border-radius: 50%;
    top: 0;
    background-color: #C0392B;
    position: absolute;
    -webkit-animation: vertical-movement 4.5s infinite ease-in-out;
    -moz-animation: vertical-movement 4.5s infinite ease-in-out;
    -ms-animation: vertical-movement 4.5s infinite ease-in-out;
    -o-animation: vertical-movement 4.5s infinite ease-in-out;
    animation: vertical-movement 4.5s infinite ease-in-out;
}

#d1 {
    left: 12px;-webkit-animation-delay: -0.3s;
    -moz-animation-delay: -0.3s;
    -ms-animation-delay: -0.3s;
    -o-animation-delay: -0.3s;
    animation-delay: -0.3s;
}

#d2 {
    left: 24px;
    -webkit-animation-delay: -0.6s;
    -moz-animation-delay: -0.6s;
    -ms-animation-delay: -0.6s;
    -o-animation-delay: -0.6s;
    animation-delay: -0.6s;
}

#d3 {
    left: 36px;
    -webkit-animation-delay: -0.9s;
    -moz-animation-delay: -0.9s;
    -ms-animation-delay: -0.9s;
    -o-animation-delay: -0.9s;
    animation-delay: -0.9s;
}

#d4 {
    left: 48px;
    -webkit-animation-delay: -1.2s;
    -moz-animation-delay: -1.2s;
    -ms-animation-delay: -1.2s;
    -o-animation-delay: -1.2s;
    animation-delay: -1.2s;
}

#d5 {
    left: 60px;
    -webkit-animation-delay: -1.5s;
    -moz-animation-delay: -1.5s;
    -ms-animation-delay: -1.5s;
    -o-animation-delay: -1.5s;
    animation-delay: -1.5s;
}

#d6 {
    left: 72px;
    -webkit-animation-delay: -1.8s;
    -moz-animation-delay: -1.8s;
    -ms-animation-delay: -1.8s;
    -o-animation-delay: -1.8s;
    animation-delay: -1.8s;
}

#d7 {
    left: 84px;
    -webkit-animation-delay: -2.1s;
    -moz-animation-delay: -2.1s;
    -ms-animation-delay: -2.1s;
    -o-animation-delay: -2.1s;
    animation-delay: -2.1s;
}

#d8 {
    left: 96px;
    -webkit-animation-delay: -2.4s;
    -moz-animation-delay: -2.4s;
    -ms-animation-delay: -2.4s;
    -o-animation-delay: -2.4s;
    animation-delay: -2.4s;
}

#d9 {
    left: 108px;
    -webkit-animation-delay: -2.7s;
    -moz-animation-delay: -2.7s;
    -ms-animation-delay: -2.7s;
    -o-animation-delay: -2.7s;
    animation-delay: -2.7s;
}

#d10 {
    left: 120px;
    -webkit-animation-delay: -3s;
    -moz-animation-delay: -3s;
    -ms-animation-delay: -3s;
    -o-animation-delay: -3s;
    animation-delay: -3s;
}

@-webkit-keyframes vertical-movement {
    0%, 100% {
        -webkit-transform: translateY(0%);
    }
    50% {
        -webkit-transform: translateY(30px);
    }
}

@keyframes vertical-movement {
    0%, 100% {
        -webkit-transform: translateY(0%);
        -moz-transform: translateY(0%);
        -ms-transform: translateY(0%);
        -o-transform: translateY(0%);
        transform: translateY(0%);
    }
    50% {
        -webkit-transform: translateY(30px);
        -moz-transform: translateY(30px);
        -ms-transform: translateY(30px);
        -o-transform: translateY(30px);
        transform: translateY(30px);
    }
}
```
