### ISSUE TITLE
Add git edit link on each page

### ISSUE THREAD

**Issue by bric3** [bric3/bric3.github.io#7]
E.g. in the footer add something like this : 

```go-template
  {{ if .File.Path }}
    {{ $.Scratch.Set "FilePath" .File.Path }}
    {{ with .Site.Params.githubEdit}}
    <a href="{{ . }}{{ $.Scratch.Get "FilePath" }}">Edit this page</a>
    {{ end }}
  {{ end }}
```

And in the `config.toml` file

```toml
[params]
  githubEdit = "https://github.com/bric3/bric3.github.io/edit/hugo-sources/"
```
